version: '3.8'

services:
  backend:
    image: django-backend  # Overridden by docker-compose.override.yml
    build:
      context: ./edtech_project
    ports:
      - "8000:8000"

  frontend:
    image: react-frontend  # Overridden by docker-compose.override.yml
    build:
      context: ./frontend
    ports:
      - "3000:3000"
