services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Backend Dockerfile should be in root
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
