name: React + Django CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend
  DJANGO_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/django-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Push React image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REACT_IMAGE }}:latest

      - name: Build & Push Django image
        uses: docker/build-push-action@v5
        with:
          context: ./edtech_project
          push: true
          tags: ${{ env.DJANGO_IMAGE }}:latest

  run-locally-with-compose:
    name: Test Docker Compose Locally
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create override to use pushed images
        run: |
          cat <<EOF > docker-compose.override.yml
          version: '3.8'
          services:
            backend:
              image: ${{ env.DJANGO_IMAGE }}:latest
              ports:
                - "8000:8000"
              container_name: django-backend
            frontend:
              image: ${{ env.REACT_IMAGE }}:latest
              ports:
                - "3000:3000"
              container_name: react-frontend
          EOF

      - name: Run Docker Compose stack
        run: docker compose up -d

      - name: Wait for services (React + Django)
        run: |
          echo "⏳ Waiting for Django..."
          sleep 10
          curl -f http://localhost:8000 || (echo "❌ Django backend failed" && exit 1)

          echo "⏳ Waiting for React..."
          curl -f http://localhost:3000 || (echo "❌ React frontend failed" && exit 1)

      - name: Shut down stack
        if: always()
        run: docker compose down
