name: React + Django CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend
  DJANGO_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/django-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Push React image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REACT_IMAGE }}:latest

      - name: Build & Push Django image
        uses: docker/build-push-action@v5
        with:
          context: ./edu_app
          push: true
          tags: ${{ env.DJANGO_IMAGE }}:latest
