name: Build and Dockerize React-Django App

on: 
    push:
        branches: [ main ]
    pull:
        branches: [ main ]
  
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  FRONTEND_IMAGE: yourusername/react-frontend
  BACKEND_IMAGE: yourusername/django-backend


jobs:
    build and deploy:
      runs-on: ubuntu-latest 
    steps:
        - name: Chechout Code
          uses: actions/checkout@v3
        
        - name: DockerHub Login
          uses: docker/login-action@v3
          with:
            username:${{env.DOCKERHUB_USERNAME}}
            password:${{env.DOCKERHUB_TOKEN}}
        -name: Build and push React frontend image
        uses: docker/build-push-action@v5
        with:
            context: ./frontend 
            file: ./frontend/Dockerfile
            push: true
            tags: ${{env.FRONTEND_IMAGE}}:latest 
        
        -name: Build and push React Backend image
        uses: docker/build-push-action@v5
        with:
            context: ./EDU_TECH
            file: ./EDU_TECH/Dockerfile
            push: true
            tags: ${{env.DACKEND_IMAGE}}:latest 
    